### ISSUE TITLE
Documentation page for node_type_set_defaults refers to hook_node_info, which is removed

### ISSUE THREAD

**Issue by jromine** [backdrop-ops/docs.backdropcms.org#194]
The documentation page: https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_set_defaults/1

refers to `hook_node_info() `which has been removed. It should perhaps refer now to `node_type_save() `instead.

**Comment by bugfolder** [comment]
Hi @jromine, thanks for finding all the docs bugs! Documentation for functions in the API comes from the docblock description for the function, which is part of Backdrop core code; so to change this documentation, one would submit a PR against Backdrop core in the usual issue queue, giving the issue a "Documentation" tag. (Also perhaps "Good first issue", since it's just a documentation change.)

So for something like this, please submit this as an issue in https://github.com/backdrop/backdrop-issues/issues.

**Comment by jromine** [comment]
Filed https://github.com/backdrop/backdrop-issues/issues/5550
