### ISSUE TITLE
Typo in the variable name on hook_boot() and hook_exit() pages

### ISSUE THREAD

**Issue by findlabnet** [backdrop-ops/docs.backdropcms.org#229]
On documentation pages https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_boot/1
and
https://docs.backdropcms.org/api/backdrop/core!modules!system!system.api.php/function/hook_exit/1

we have typo: instead 'page_cache_invoke_hook' should be 'page_cache_invoke_hooks' as in `bootstrap.inc` file, lines 3099 and 3116.

**Comment by argiepiano** [comment]
Good catch! Those pages are produced from the actual documentation in the code. So this typo must be fixed in core, in file `system.api.php`; then it will be fixed on that documentation page. Can you please open an issue in the main backdrop issues queue?

By the way, there is another spot where this is mistyped in core - documentation for hook_exit()

**Comment by findlabnet** [comment]
Done. https://github.com/backdrop/backdrop-issues/issues/6273

**Comment by bugfolder** [comment]
PR submitted. https://github.com/backdrop/backdrop/pull/4934

**Comment by bugfolder** [comment]
Fix has been merged. Thanks, @findlabnet!
