### ISSUE TITLE
Documentation - Update Core via UI (Project Installer required)

### ISSUE THREAD

**Issue by rombpat** [backdrop-ops/docs.backdropcms.org#241]
Page to update: Core Updates (https://docs.backdropcms.org/documentation/core-updates)

Issue: it seems that the "System Updates" page is only available when the "Project Installer" module is enabled, which the Core Updates documentation page doesn't mention.

Therefore I suggest  to update step 5 of the Core Updates documentation page as follows (**changes in bold**): 

> 5. Navigate to the **System** Updates page. This can be accessed in a few different ways:
> - Go from the list of Available updates at /admin/reports/updates/list following the "Install system updates" link at the top.
> - Navigate directly to the page using the URL (admin/config/system/updates) or the Admin menu (Configuration > System > System updates) 
> - Follow the link in the Status report under Backdrop CMS update status. 
>
>
> **Note: If you don't see the "Install system updates" link or the "System updates" menu item, make sure that the Project Installer module is enabled at /admin/modules/list.**
>
>  

PS: in the first sentence of step 5 I also suggest to change the current "Updates page" to the more explicit "System Updates page"

**Comment by bugfolder** [comment]
Hi @rombpat, thanks for posting this issue. I completely agree with the need for making clear the need for the "Project Installer" module to run updates from the UI. When reading through that page, I saw a lot of other areas for improvement, so I've taken the liberty of incorporating your suggestion into a more thorough rewrite of that page.

The documentation pages accept Markdown format, so I've put together two files, attached here: the existing text in Markdown format, and a suggested rewrite. I"ll solicit further comments or suggestions for change. (Pinging @jenlampton in particular to take a look.)

[updates_old.md](https://github.com/user-attachments/files/18040733/updates_old.md)
[updates_new.md](https://github.com/user-attachments/files/18040735/updates_new.md)

**Comment by jenlampton** [comment]
@bugfolder  Thank you for taking the time :) and @rombpat  thank you for the suggestion!

I'd love to review the rewrite. 
Would it be possible copy/paste the markdown into this issue or something that doesn't require a file download (a gist maybe?). I can read/respond from my phone - but I don't have any tools there that would allow opening a markdown file.

**Comment by bugfolder** [comment]
Here's the code in this comment.
- - - - -
- Minor and patch updates are straight-forward, and usually may be done independently of any module updates. It's usually a good idea to update Backdrop CMS core independently, before attempting any module updates.
You can update Backdrop CMS core code directly if you have FTP access to your hosting service or via the UI; both are described below.

## Preliminaries: Back It Up

1.  **Make a backup of your database**.
2.  **Make a backup of the active configdirectory** (located at files/config\_\[hash\]/active unless otherwise specified in the settings.php file).
3.  Login to your site as a user with the "Administrator" role.
4.  Put your site into maintenance mode (optional, but **strongly recommended**) at /admin/config/development/maintenance (Configuration > Development > Maintenance mode).

## Check the Update

1. Go to the list of available updates at /admin/reports/updates/list. If a Backdrop CMS update is available, it will be listed there as the first item on the list.
6. Check the Release notes for anything to be aware of. There will be a link in the table under "Recommended Version".
    *   **Note**: If any of the files outside the core directory have been changed and need to also be updated, they will be explicitly mentioned in the release notes. These will not be changed by the System Updater (to avoid overwriting any changes you have made) and may need manually updating; there will be instructions in the release notes.

## Update Core Code

If you have FTP access to your site, you can download the latest Backdrop CMS code using the Download link on that page and replace the corresponding files at your site's host, or you can use the System Updater to update the code from within the Backdrop CMS UI.

### Updating Core Code Directly

To update core code directly, e.g., by uploading files via FTP, do the following:

1. Download the core code using the Download link for Backdrop CMS and expand the .zip file.
2. Upload the "core" directory from your download to replace the corresponding "core" directory in your site files.
3. If the release notes noted changes in the .htaccess or robots.txt file, replace those files in your site files with the new ones. If you have modified those files, you will have to merge the changes into your modified files.
4. Go to the "Backdrop Site Update" page at /core/update.php

### Updating Core Code from the UI

To update the core code using the System Updater from the UI, you will have to have the Project Installer module enabled on your site:

1. Navigate to /admin/modules/list (Functionality > List modules) and look for the Project Installer module; if it is not checked, check its box and then click "Save Configuration." If it is already checked, proceed.
2. Navigate to the System Updates page. This can be accessed in a few different ways:
    *   Go from the list of Available updates at /admin/reports/updates/list following the "Install system updates" link at the top.
    *   Navigate directly to the page using the URL (admin/config/system/updates) or the Admin menu (Configuration > System > System updates)
    *   Follow the link in the Status report under Backdrop CMS update status.
3.  Select "Backdrop" to update core, click "Download Selected Updates" and the updater will download the new version and take you to the "Ready to update" page.
4.  If you haven't already put the site into maintenance mode you should check the box to put it into maintenance mode for this next step.
5.  Click 'Continue' and the update will be applied.
6. There will be a link to "Run site updates"; follow that link. You can also access that page by going to core/update.php (e.g. [https://example.com/core/update.php](https://example.com/core/update.php)).

## Running Site Updates

After updating core code via either method, continue as follows (you will be on the "Run site updates" page at /core/update.php):

1.  After checking that you are happy with all your backups, click Continue
2.  If any errors have appeared, these will need to be addressed and you may need to run the update again. Help is available in the [Forum](https://forum.backdropcms.org/forum/how-and-troubleshooting) or the [chat channel](https://backdrop.zulipchat.com/ "Zulip Chat for Backdrop CMS").
3.  If no errors are shown then everything has been updated successfully.
4.  If you turned on the maintenance mode option, turn it back off at /admin/config/development/maintenance (Configuration > Development > Maintenance mode) to make your site publicly accessible again.

**Comment by jenlampton** [comment]
Thanks @bugfolder, I appreciate you taking the time to add the text here - and I appreciate even more the fantastic docs update!  

I think that the UI-based update instructions should come before the FTP instructions, catering to our "less-technical solutions first" methodology :) 

In the paragraph Under `Update Core Code` I would rearrange the paragraph, something like...  

> The Backdrop Installer module can be used to update the code from within the Backdrop CMS admin interface. If you would prefer not to enable the installer module enabled on a production site, another option would be update the code via FTP.  You can download the latest Backdrop CMS code using the Download link on backdropcms.org, and replace the corresponding files at your site's host (assuming you have FTP access to your site).

Then move the `Updating Core Code Directly` section below `Updating Core Code from the UI` :)

Other minor thoughts:

I would change `Back It Up` to `Make a backup`
I would change `Check the Update` to `Check for updates`
I would replace `UI` with `Admin interface` or even `Administrative interface`
In the `Updating Core Code from the UI` section, I would end with disabling/uninstalling project installer, but you can mark that as optional :) 
And in step 2, it might be helpful to mention that if the "Install system updates" link is missing, you should check permissions for installer module

In general, I love this! thank you.

**Comment by bugfolder** [comment]
All changes made, thanks for the suggestions. Here's the revised version, for final checking before deployment.
- - - - -
Minor and patch updates are straight-forward, and usually may be done independently of any module updates. It's usually a good idea to update Backdrop CMS core independently, before attempting any module updates.
You can update Backdrop CMS core code via the administrative interface or directly if you have FTP access to your hosting service; both are described below.

## Preliminaries: Make a Backup

1.  **Make a backup of your database**.
2.  **Make a backup of the active config directory** (located at files/config\_\[hash\]/active unless otherwise specified in the settings.php file).
3.  Login to your site as a user with the "Administrator" role.
4.  Put your site into maintenance mode (optional, but **strongly recommended**) at /admin/config/development/maintenance (Configuration > Development > Maintenance mode).

## Check for Updates

1. Go to the list of available updates at /admin/reports/updates/list. If a Backdrop CMS update is available, it will be listed there as the first item on the list.
6. Check the Release notes for anything to be aware of. There will be a link in the table under "Recommended Version".
    *   **Note**: If any of the files outside the core directory have been changed and need to also be updated, they will be explicitly mentioned in the release notes. These will not be changed by the System Updater (to avoid overwriting any changes you have made) and may need manually updating; there will be instructions in the release notes.

## Update Core Code

If you have FTP access to your site, you can download the latest Backdrop CMS code using the Download link on that page and replace the corresponding files at your site's host, or you can use the System Updater to update the code from within the Backdrop CMS UI.

### Updating Core Code via the Adminstrative Interface

To update the core code using the System Updater in the administrative area of the website, you will have to have the Project Installer module enabled on your site:

1. Navigate to /admin/modules/list (Functionality > List modules) and look for the Project Installer module; if it is not checked, check its box and then click "Save Configuration." If it is already checked, proceed.
2. Navigate to the System Updates page. This can be accessed in a few different ways:
    *   Go from the list of Available updates at /admin/reports/updates/list following the "Install system updates" link at the top.
    *   Navigate directly to the page using the URL (admin/config/system/updates) or the Admin menu (Configuration > System > System updates)
    *   Follow the link in the Status report under Backdrop CMS update status.
    *   If the "Install system updates" link is missing, you should check permissions for the Project Installer module.
3.  Select "Backdrop" to update core, click "Download Selected Updates" and the updater will download the new version and take you to the "Ready to update" page.
4.  If you haven't already put the site into maintenance mode you should check the box to put it into maintenance mode for this next step.
5.  Click 'Continue' and the update will be applied.
6. There will be a link to "Run site updates"; follow that link. You can also access that page by going to core/update.php (e.g. [https://example.com/core/update.php](https://example.com/core/update.php)).

### Updating Core Code Directly

To update core code directly, e.g., by uploading files via FTP, do the following:

1. Download the core code using the Download link for Backdrop CMS and expand the .zip file.
2. Upload the "core" directory from your download to replace the corresponding "core" directory in your site files.
3. If the release notes noted changes in the .htaccess or robots.txt file, replace those files in your site files with the new ones. If you have modified those files, you will have to merge the changes into your modified files.
4. Go to the "Backdrop Site Update" page at /core/update.php

## Running Site Updates

After updating core code via either method, continue as follows (you will be on the "Run site updates" page at /core/update.php):

1.  After checking that you are happy with all your backups, click Continue
2.  If any errors have appeared, these will need to be addressed and you may need to run the update again. Help is available in the [Forum](https://forum.backdropcms.org/forum/how-and-troubleshooting) or the [chat channel](https://backdrop.zulipchat.com/ "Zulip Chat for Backdrop CMS").
3.  If no errors are shown then everything has been updated successfully.
4.  If you turned on the maintenance mode option, turn it back off at /admin/config/development/maintenance (Configuration > Development > Maintenance mode) to make your site publicly accessible again.

If you used the administrative interface to update core code, you may disable and, if you wish, uninstall the Project Installer module, or you can leave it in place for the next time you update core code.

[updates_new.md](https://github.com/user-attachments/files/18105121/updates_new.md)

**Comment by jenlampton** [comment]
This looks great, with the exception of the order of updates in the paragraph below `Update Core Code`:

> If you have FTP access to your site, you can download the latest Backdrop CMS code using the Download link on that page and replace the corresponding files at your site's host, or you can use the System Updater to update the code from within the Backdrop CMS administrative interface.

I would switch this around so that we don't scare people away by mentioning `FTP` first thing :) I had an example in my last comment, but if you don't like that we could just topsy-turvy the two parts of this one.

**Comment by bugfolder** [comment]
I just missed your paragraph. I've added it (though used the name of the module, Project Installer, rather than "Backdrop Installer"). Hopefully this is now OK, please do a final check:
- - - - - 
Minor and patch updates are straight-forward, and usually may be done independently of any module updates. It's usually a good idea to update Backdrop CMS core independently, before attempting any module updates.
You can update Backdrop CMS core code via the administrative interface or directly if you have FTP access to your hosting service; both are described below.

## Preliminaries: Make a Backup

1.  **Make a backup of your database**.
2.  **Make a backup of the active config directory** (located at files/config\_\[hash\]/active unless otherwise specified in the settings.php file).
3.  Login to your site as a user with the "Administrator" role.
4.  Put your site into maintenance mode (optional, but **strongly recommended**) at /admin/config/development/maintenance (Configuration > Development > Maintenance mode).

## Check for Updates

1. Go to the list of available updates at /admin/reports/updates/list. If a Backdrop CMS update is available, it will be listed there as the first item on the list.
6. Check the Release notes for anything to be aware of. There will be a link in the table under "Recommended Version".
    *   **Note**: If any of the files outside the core directory have been changed and need to also be updated, they will be explicitly mentioned in the release notes. These will not be changed by the System Updater (to avoid overwriting any changes you have made) and may need manually updating; there will be instructions in the release notes.

## Update Core Code

The Project Installer module can be used to update the code from within the Backdrop CMS admin interface. If you would prefer not to enable the installer module enabled on a production site, another option would be update the code via FTP. You can download the latest Backdrop CMS code using the Download link on backdropcms.org, and replace the corresponding files at your site's host (assuming you have FTP access to your site).

### Updating Core Code via the Adminstrative Interface

To update the core code using the System Updater in the administrative area of the website, you will have to have the Project Installer module enabled on your site:

1. Navigate to /admin/modules/list (Functionality > List modules) and look for the Project Installer module; if it is not checked, check its box and then click "Save Configuration." If it is already checked, proceed.
2. Navigate to the System Updates page. This can be accessed in a few different ways:
    *   Go from the list of Available updates at /admin/reports/updates/list following the "Install system updates" link at the top.
    *   Navigate directly to the page using the URL (admin/config/system/updates) or the Admin menu (Configuration > System > System updates)
    *   Follow the link in the Status report under Backdrop CMS update status.
    *   If the "Install system updates" link is missing, you should check permissions for the Project Installer module.
3.  Select "Backdrop" to update core, click "Download Selected Updates" and the updater will download the new version and take you to the "Ready to update" page.
4.  If you haven't already put the site into maintenance mode you should check the box to put it into maintenance mode for this next step.
5.  Click 'Continue' and the update will be applied.
6. There will be a link to "Run site updates"; follow that link. You can also access that page by going to core/update.php (e.g. [https://example.com/core/update.php](https://example.com/core/update.php)).

### Updating Core Code Directly

To update core code directly, e.g., by uploading files via FTP, do the following:

1. Download the core code using the Download link for Backdrop CMS and expand the .zip file.
2. Upload the "core" directory from your download to replace the corresponding "core" directory in your site files.
3. If the release notes noted changes in the .htaccess or robots.txt file, replace those files in your site files with the new ones. If you have modified those files, you will have to merge the changes into your modified files.
4. Go to the "Backdrop Site Update" page at /core/update.php

## Running Site Updates

After updating core code via either method, continue as follows (you will be on the "Run site updates" page at /core/update.php):

1.  After checking that you are happy with all your backups, click Continue.
2.  If any errors have appeared, these will need to be addressed and you may need to run the update again. Help is available in the [Forum](https://forum.backdropcms.org/forum/how-and-troubleshooting) or the [chat channel](https://backdrop.zulipchat.com/ "Zulip Chat for Backdrop CMS").
3.  If no errors are shown then everything has been updated successfully.
4.  If you turned on the maintenance mode option, turn it back off at /admin/config/development/maintenance (Configuration > Development > Maintenance mode) to make your site publicly accessible again.

If you used the administrative interface to update core code, you may disable and, if you wish, uninstall the Project Installer module, or you can leave it in place for the next time you update core code.

[updates_new.md](https://github.com/user-attachments/files/18119829/updates_new.md)

**Comment by jenlampton** [comment]
Looks good to me, but I'd love a other set of eyes. Maybe we post now and
then ask for feedback on e it's up?

**Comment by bugfolder** [comment]
Posted and feeback solicited: https://backdrop.zulipchat.com/#narrow/channel/279369-Backdrop-Infrastructure/topic/Documentation/near/489121532
