### ISSUE TITLE
Change coding standards for colors in CSS

### ISSUE THREAD

**Issue by hosef** [backdrop-ops/docs.backdropcms.org#50]
As part of the HTML 5 spec, HTML now supports special inputs for specifying colors with browser provided color pickers, however this functionality only works if the default value is a 6 character color code. For us to be able to use the HTML color input for the color module, then the color codes in our CSS files need to be changed. Therefore, I recommend changing the coding standards for CSS files to use 6 character color codes.
http://w3c.github.io/html-reference/input.color.html#input.color.attrs.value
https://codepen.io/hosef/pen/BVVbvV

**Comment by BWPanda** [comment]
@hosef I don't quite understand this... If 6-digit color codes are needed for HTML input elements, why do CSS files need to change? Or if the result of selecting a color from the widget writes that color to the CSS, it'll write the 6-digits, so what does it matter what existing values are?

Sorry that I'm probably just not understanding you properly...

**Comment by indigoxela** [comment]
I've been asked to also post this here in the backdrop-ops queue:

A word of warning: changing color definitions from long to short, for instance `background: #dddddd;` to `background: #ddd;` will have negative side effects. The color module will not be able to replace these values, as it relies on the long form. Which means, that color presets might break.

**Comment by BWPanda** [comment]
@indigoxela Are you able to clarify as per my question above? I don't understand how/why this is needed...

**Comment by indigoxela** [comment]
> Are you able to clarify as per my question above? I don't understand how/why this is needed...

Unfortunately I can't point you to the exact code line, but it has always been this way - since I created color presets - for D and B. Short color definitions won't get replaced by the color module.

**Comment by BWPanda** [comment]
Or we could just fix the bug in Color module instead: https://github.com/backdrop/backdrop-issues/issues/4913 😉 

Found the issue. Color was already kind of supporting short codes (https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/modules/color/color.module#L675) but then wasn't matching against them properly (https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/modules/color/color.module#L685).

If you're happy with fixing Color module instead of changing our coding standards, we can close this issue.

**Comment by jenlampton** [comment]
In the weekly dev meeting today it sounds like we wanted to do both :)

* fix the bug in color module (thank you for the PR!) 
* and change the coding standards to switch to a 6-digit hex code.

**Comment by BWPanda** [comment]
In retrospect, I think I agree with changing the coding standards to long hex codes instead of short - mainly because of consistency:

- Not all colours can be represented with short codes, so by recommending short codes we'll end up with both long and short in core
- All colours can be represented with with long codes, so by recommending long codes there won't be a combination of both in core

**Comment by klonos** [comment]
Yeah, as also mentioned during the dev call, I think that the main reasons for the 3-character short codes were "type less", and "reduce size of CSS files". I don't think that these reasons offer much gain nowadays, and I also value consistency over them.

**Comment by hosef** [comment]
@BWPanda @indigoxela The issue I was bringing up is only an issue when we send the default value in the HTML of the form.
If you send `<input type="color" value="#ffffff">` to the browser it works as expected, but if you send `<input type="color" value="#fff">` to the browser it will act like the 'value' property does not exist.

**Comment by klonos** [comment]
It seems that the people that have chimed in here are in agreement re changing the coding standard, which will bring consistency + address a known issue. So what next? Do we simply update the wording and code examples in https://docs.backdropcms.org/css-standards?

**Comment by jenlampton** [comment]
I would say yes?

**Comment by BWPanda** [comment]
Done! https://docs.backdropcms.org/css-standards That addresses this issue, so closing now.
